baseURL = "http://aksharpatel47.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Akshar's Website"
theme = "anatole"
enableEmoji = true

# Enable Disqus
disqusShortname = "aksharpatel47"

# Google Analytics
googleAnalytics = "UA-51408306-2"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
title = "Forever Learning Diary"
author = "Akshar Patel"
description = "Writing on Apps, APIs, Ops, and ML."
profilePicture = "images/profile.jpg"
keywords = "blogs,portfolio"
favicon = "favicons/"
customCss = []
mainSections = ["posts"]

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"


[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/aksharpatel47"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/aksharpatel47"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/aksharpatel47"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:akshar.patel47@gmail.com"
