FROM alpine:latest

RUN wget https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.tar.gz && \
    mkdir hugo && tar -xf hugo_0.72.0_Linux-64bit.tar.gz --directory hugo && mv hugo/hugo /usr/bin \
    && rm -rf hugo && rm hugo_0.72.0_Linux-64bit.tar.gz

