name: Create Docker Image
run-name: Create Docker Image from ${{ github.ref_name }}. Build No - ${{ github.run_number }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: aksharpatel47/kube-charts
          path: kube-charts
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/me" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}-${{ github.run_number }}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: update image tag in kube-charts
        run: |
          sed -i "s|ghcr.io/aksharpatel47/me:.*|ghcr.io/aksharpatel47/me:${{ github.IMAGE_TAG }}|g" kube-charts/me/base/deployment.yml
          (cd kube-charts && git config --global user.email akshar.patel.47@gmail.com)
          (cd kube-charts && git config --global user.name aksharpatel47)
          (cd kube-charts && git add me/base/deployment.yml)
          (cd kube-charts && git commit -m "Update image tag for me deployment to ${{ github.IMAGE_TAG }}")
          (cd kube-charts && git push origin main)
          
          
        
